INSERT INTO PUBLISHERS (PUBLICATION_NAME)
VALUES
    ('TechPress'),
    ('CodeBooks Publishing'),
    ('ByteHouse Publications'),
    ('InnoTech Publishers'),
    ('DataDriven Books'),
    ('Algorithmic Insights'),
    ('Bitwise Publications'),
    ('Digital Trends Press'),
    ('Binary Books Co.'),
    ('Cloud Computing Publishing'),
    ('Software Spectrum Publications'),
    ('Tech Innovators Press'),
    ('CyberNet Publishers'),
    ('LogicLab Books'),
    ('Network Nexus Publishing'),
    ('AI Solutions Books'),
    ('TechCraft Publishers'),
    ('Quantum Quotient Books'),
    ('Virtual World Press'),
    ('WebWizards Publishing'),
    ('Future Focus Books'),
    ('Big Data Books Co.'),
    ('RoboRealm Publications'),
    ('CircuitScribe Press'),
    ('EcoCode Publishers'),
    ('InfoSphere Books'),
    ('NeuralNet Publications'),
    ('Digital Dynamics Press'),
    ('CyberCraft Books'),
    ('Smart Systems Publishing'),
    ('TechTrek Books'),
    ('QuantumQuest Publications'),
    ('AlgoByte Press'),
    ('DataWare Books Co.'),
    ('VirtualVision Publishers'),
    ('CodeCraft Press'),
    ('NetworkNovel Publications'),
    ('AI Architects Books'),
    ('TechFusion Publishing'),
    ('InnoData Books'),
    ('WebWizardry Press'),
    ('TechTopia Publishers'),
    ('QuantumLeap Books Co.'),
    ('AlgorithmicArt Publications'),
    ('DataSphere Press'),
    ('VirtualReality Books'),
    ('CircuitCraft Publishers'),
    ('AIAdvantage Books'),
    ('TechInsights Publishing'),
    ('CodeSculpture Press'),
    ('BanglaTech Publishers'),
    ('DhakaData Books'),
    ('TechBD Press'),
    ('DigitalDhaka Publications'),
    ('CodeCrafters BD Books'),
    ('DataSphere Bangladesh Press'),
    ('CircuitSolutions BD'),
    ('InnoTech BD Publishers'),
    ('ByteBangla Books'),
    ('WebWizards BD Publishing'),
    ('BangladeshTech Press'),
    ('CloudCode BD Publications'),
    ('AI Bangladesh Books'),
    ('RoboCraft BD Press'),
    ('LogicLab BD Publications'),
    ('NetworkNovel BD Books'),
    ('TechFusion Bangladesh Publishers'),
    ('QuantumQuest BD Books'),
    ('VirtualVision BD Publishers'),
    ('WebWizardry Bangladesh Press'),
    ('Future Focus BD Books'),
    ('Big Data Bangladesh Publications'),
    ('RoboRealm Bangladesh Press'),
    ('CircuitScribe BD Publishers'),
    ('EcoCode Bangladesh Books'),
    ('InfoSphere BD Press'),
    ('NeuralNet Bangladesh Publications'),
    ('Digital Dynamics BD Books'),
    ('CyberCraft BD Press'),
    ('Smart Systems Bangladesh Publishers'),
    ('TechTrek BD Books'),
    ('QuantumQuest Bangladesh Publications'),
    ('AlgoByte BD Press'),
    ('DataWare BD Books'),
    ('VirtualVision Bangladesh Publishers'),
    ('CodeCraft BD Press'),
    ('NetworkNovel Bangladesh Publications'),
    ('AI Architects BD Books'),
    ('TechFusion BD Publishers'),
    ('InnoData BD Books'),
    ('WebWizardry BD Press'),
    ('TechTopia Bangladesh Publishers'),
    ('QuantumLeap BD Books'),
    ('AlgorithmicArt Bangladesh Press'),
    ('DataSphere BD Publications'),
    ('VirtualReality BD Books'),
    ('CircuitCraft Bangladesh Publishers'),
    ('AIAdvantage BD Books'),
    ('TechInsights Bangladesh Press'),
    ('CodeSculpture BD Publishers');
