INSERT INTO BOOKS (TITLE, CATEGORY, PUBLISHER_ID, SHELF_ID) 
VALUES 
('The Adventure Begins', 'Computer Science', 3, 1),
('Coding Essentials', 'Electrical Engineering', 6, 2),
('Secrets of the Universe', 'Mechanical Engineering', 9, 3),
('Gourmet Delights', 'Civil Engineering', 12, 4),
('Ancient Civilizations', 'Chemical Engineering', 15, 5),
('Expressions of the Soul', 'Biomedical Engineering', 18, 6),
('Mathematics Made Easy', 'Information Technology', 21, 7),
('Eternal Love Stories', 'Electronic Engineering', 24, 8),
('The Enchanted Forest', 'Aerospace Engineering', 27, 9),
('Journey to the Stars', 'Materials Science', 30, 10),
('Healthy Living Guide', 'Environmental Engineering', 33, 11),
('Digital Art Masterclass', 'Industrial Engineering', 36, 12),
('Financial Wisdom', 'Software Engineering', 39, 13),
('Wildlife Photography', 'Telecommunication Engineering', 42, 14),
('Mindful Meditation', 'Robotics', 45, 15),
('Astrology Unveiled', 'Networks', 48, 16),
('World of Inventions', 'Control Systems', 51, 17),
('DIY Home Decor', 'Renewable Energy', 54, 18),
('Culinary Adventures', 'Artificial Intelligence', 57, 19),
('Space Exploration', 'Data Science', 60, 20),
('Epic Fantasy Quest', 'Structural Engineering', 63, 1),
('Code Breaker', 'Geotechnical Engineering', 66, 2),
('Lost in Time', 'Computer Networks', 69, 3),
('Love in Bloom', 'Computer Architecture', 72, 4),
('The Art of Painting', 'Database Systems', 75, 5),
('The Quantum Realm', 'Digital Signal Processing', 78, 6),
('Healthy Recipes', 'Embedded Systems', 81, 7),
('Poetic Whispers', 'Machine Learning', 84, 8),
('The Mindful Path', 'Software Development', 87, 9),
('Mathematical Marvels', 'Cybersecurity', 90, 10),
('Fictional Realms', 'Wireless Communication', 93, 11),
('Tech Innovations', 'VLSI Design', 96, 12),
('Natures Beauty', 'Renewable Energy Systems', 99, 13),
('The Culinary Artist', 'Materials Processing', 2, 14),
('Mysteries Unveiled', 'Biomechanics', 5, 15),
('Artistic Expressions', 'Medical Imaging', 8, 16),
('Astronomy Explorations', 'Telecommunication Networks', 11, 17),
('Beyond the Horizon', 'Human-Computer Interaction', 14, 18),
('Coding for Beginners', 'Optical Communication', 17, 19),
('Whispers of the Past', 'Structural Dynamics', 20, 20),
('Timeless Tales', 'Transportation Engineering', 2, 1),
('Algorithmic Adventures', 'Hydraulic Engineering', 4, 2),
('The Scientific Mind', 'Energy Systems', 6, 3),
('Flavors of the World', 'Renewable Energy Technologies', 8, 4),
('Civilizations Through Ages', 'Sustainable Design', 10, 5),
('Verses of the Heart', 'Data Mining', 12, 6),
('Advanced Calculus', 'Cloud Computing', 14, 7),
('Love in the Air', 'Mobile Computing', 16, 8),
('Enchanting Creatures', 'Digital Systems Design', 18, 9),
('Galactic Odyssey', 'Computer Graphics', 20, 10),
('Mind and Body Harmony', 'Information Retrieval', 22, 11),
('Digital Artistry', 'Network Security', 24, 12),
('Financial Insights', 'Computer Vision', 26, 13),
('Wildlife Wonders', 'Humanoid Robotics', 28, 14),
('Zen Moments', 'Power Systems', 30, 15),
('Celestial Alignments', 'Control Theory', 32, 16),
('Innovative Inventions', 'Renewable Energy Policy', 34, 17),
('Creative DIY Projects', 'Engineering Ethics', 36, 18),
('Gastronomic Delights', 'Nanoengineering', 38, 19),
('Exploring the Cosmos', 'Renewable Energy Economics', 40, 20),
('Heroic Tales', 'Geographic Information Systems', 42, 1),
('Code Mastery', 'Artificial Neural Networks', 44, 2),
('Time Travel Chronicles', 'Fuzzy Logic', 46, 3),
('Romantic Escapes', 'Mobile Robotics', 48, 4),
('Brushstrokes of Beauty', 'Advanced Database Systems', 50, 5),
('Quantum Physics Revealed', 'Digital Image Processing', 52, 6),
('Deliciously Healthy', 'Telecommunication Policy', 54, 7),
('Whispers of Eternity', 'Human-Robot Interaction', 56, 8),
('Journey to Serenity', 'Renewable Energy Management', 58, 9),
('Advanced Algebra', 'Structural Health Monitoring', 60, 10),
('Imaginary Realms', 'Biomedical Signal Processing', 62, 11),
('Tech Trends', 'Wireless Sensor Networks', 64, 12),
('Natures Harmony', 'Cloud Security', 66, 13),
('The Culinary Maestro', 'Renewable Energy and Society', 68, 14),
('Cryptic Mysteries', 'Computational Biology', 70, 15),
('Expressive Art Forms', 'Internet of Things', 72, 16),
('Stellar Explorations', 'Parallel Computing', 74, 17),
('Uncharted Territories', 'Renewable Energy Innovations', 76, 18),
('Coding Prodigy', 'Smart Cities', 78, 19),
('Echoes of the Past', 'Renewable Energy Materials', 80, 20),
('Epic Journeys', 'Advanced Robotics', 73, 1),
('Code Breakthrough', 'Renewable Energy Storage', 29, 2),
('Beyond the Cosmos', 'Renewable Energy Modeling', 41, 3),
('Culinary Masterclass', 'Digital Forensics', 11, 4),
('Legends of the Past', 'Natural Language Processing', 87, 5),
('Whispers of Nature', 'Digital Marketing', 53, 6),
('Digital Creativity', 'Human-Centered Design', 17, 7),
('Financial Strategies', 'Electrical Engineering', 67, 8),
('The Mindful Explorer', 'Mechanical Engineering', 91, 9),
('Poetic Inspirations', 'Civil Engineering', 31, 10),
('The Quantum Code', 'Chemical Engineering', 47, 11),
('Romantic Moments', 'Biomedical Engineering', 79, 12),
('Fantasy Realms', 'Information Technology', 37, 13),
('Photographic Journeys', 'Electronic Engineering', 23, 14),
('Healthy Living Handbook', 'Aerospace Engineering', 71, 15),
('Astrological Insights', 'Materials Science', 13, 16),
('Innovative Gadgets', 'Environmental Engineering', 59, 17),
('Home DIY Projects', 'Industrial Engineering', 83, 18),
('Gastronomic Adventures', 'Software Engineering', 43, 19),
('Exploring the Stars', 'Telecommunication Engineering', 97, 20),
('Chronicles of Heroes', 'Robotics', 14, 1),
('Programming Wizardry', 'Networks', 92, 2),
('Timeless Love Stories', 'Control Systems', 62, 3),
('Artistic Expressions II', 'Renewable Energy', 50, 4),
('Unveiling Mysteries', 'Artificial Intelligence', 26, 5),
('The Wisdom of Ages', 'Data Science', 76, 6),
('Digital Marketing Mastery', 'Structural Engineering', 68, 7),
('Soulful Meditations', 'Geotechnical Engineering', 34, 8),
('Poetry of the Heart', 'Computer Networks', 80, 9),
('Mastering Calculus', 'Computer Architecture', 56, 10),
('Fictional Wonders', 'Database Systems', 38, 11),
('Tech Innovations II', 'Digital Signal Processing', 74, 12),
('Natures Beauty II', 'Embedded Systems', 44, 13),
('The Culinary Artist II', 'Machine Learning', 20, 14),
('Cryptic Enigmas', 'Software Development', 32, 15),
('Visual Arts Showcase', 'Cybersecurity', 86, 16),
('Celestial Wonders', 'Wireless Communication', 98, 17),
('Adventures Beyond', 'VLSI Design', 5, 18),
('Programming Prowess', 'Renewable Energy Systems', 53, 19),
('Historical Chronicles II', 'Materials Processing', 8, 20);
