INSERT INTO CATEGORIES (CATEGORY)
VALUES
    ('Computer Science'),
    ('Electrical Engineering'),
    ('Mechanical Engineering'),
    ('Civil Engineering'),
    ('Chemical Engineering'),
    ('Biomedical Engineering'),
    ('Information Technology'),
    ('Electronic Engineering'),
    ('Aerospace Engineering'),
    ('Materials Science'),
    ('Environmental Engineering'),
    ('Industrial Engineering'),
    ('Software Engineering'),
    ('Telecommunication Engineering'),
    ('Robotics'),
    ('Networks'),
    ('Control Systems'),
    ('Renewable Energy'),
    ('Artificial Intelligence'),
    ('Data Science'),
    ('Structural Engineering'),
    ('Geotechnical Engineering'),
    ('Computer Networks'),
    ('Computer Architecture'),
    ('Database Systems'),
    ('Digital Signal Processing'),
    ('Embedded Systems'),
    ('Machine Learning'),
    ('Software Development'),
    ('Cybersecurity'),
    ('Wireless Communication'),
    ('VLSI Design'),
    ('Renewable Energy Systems'),
    ('Materials Processing'),
    ('Biomechanics'),
    ('Medical Imaging'),
    ('Telecommunication Networks'),
    ('Human-Computer Interaction'),
    ('Optical Communication'),
    ('Structural Dynamics'),
    ('Transportation Engineering'),
    ('Hydraulic Engineering'),
    ('Energy Systems'),
    ('Renewable Energy Technologies'),
    ('Sustainable Design'),
    ('Data Mining'),
    ('Cloud Computing'),
    ('Mobile Computing'),
    ('Digital Systems Design'),
    ('Computer Graphics'),
    ('Information Retrieval'),
    ('Network Security'),
    ('Computer Vision'),
    ('Humanoid Robotics'),
    ('Power Systems'),
    ('Control Theory'),
    ('Renewable Energy Policy'),
    ('Engineering Ethics'),
    ('Nanoengineering'),
    ('Renewable Energy Economics'),
    ('Geographic Information Systems'),
    ('Artificial Neural Networks'),
    ('Fuzzy Logic'),
    ('Mobile Robotics'),
    ('Advanced Database Systems'),
    ('Digital Image Processing'),
    ('Telecommunication Policy'),
    ('Human-Robot Interaction'),
    ('Renewable Energy Management'),
    ('Structural Health Monitoring'),
    ('Biomedical Signal Processing'),
    ('Wireless Sensor Networks'),
    ('Cloud Security'),
    ('Renewable Energy and Society'),
    ('Computational Biology'),
    ('Internet of Things'),
    ('Parallel Computing'),
    ('Renewable Energy Innovations'),
    ('Smart Cities'),
    ('Renewable Energy Materials'),
    ('Advanced Robotics'),
    ('Renewable Energy Storage'),
    ('Renewable Energy Modeling'),
    ('Digital Forensics'),
    ('Natural Language Processing'),
    ('Digital Marketing'),
    ('Human-Centered Design');

